/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React from 'react';
import { Paper, JournalArticle } from './types';

export const BRAND_NAME = 'ClayMind';

export const GLOSSARY: Record<string, string> = {
  "Algorithm": "A set of rules or instructions given to an AI to help it solve a problem or complete a task.",
  "Machine Learning": "A way for computers to learn from data without being explicitly programmed for every step.",
  "Bias": "When an AI makes unfair decisions because the data it learned from was incomplete or unfair.",
  "Deepfake": "A video or image generated by AI that looks real but is actually fake.",
  "Digital Footprint": "The trail of data you leave behind when you use the internet.",
  "Neural Network": "A computer system designed to mimic the way the human brain learns and processes information.",
  "Phishing": "A trick used by scammers to get you to reveal private information like passwords.",
  "Chatbot": "A computer program designed to simulate conversation with human users.",
  "Privacy": "The right to keep your personal information safe and secret from others.",
  "Misinformation": "False or inaccurate information that is spread, regardless of whether there is an intent to deceive.",
  "Prompt": "The text input you give to an AI to tell it what to do.",
  "Data": "Information, facts, or numbers that computers use to learn and make decisions."
};

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    id: 1,
    title: 'Why AI Needs "Data Nutrition Labels"',
    date: 'Current Issue',
    excerpt: 'Just like food, we need to know what goes into the AI models we use. Understanding data quality helps us spot bias.',
    content: React.createElement('p', null, 'Before trusting an AI, we must ask: Where did it learn this? "Data Nutrition Labels" are a proposed standard to show the ingredients of a dataset, helping students and teachers identify potential biases and gaps in knowledge.')
  },
  {
    id: 2,
    title: 'The Great Deepfake Detective',
    date: 'Safety Guide',
    excerpt: 'How to spot AI-generated images and videos in your social feed using critical thinking and visual clues.',
    content: React.createElement('p', null, 'AI is getting better at making fake images, but it often struggles with details. Look for mismatched earrings, weird hands, or text that doesn\'t make sense in the background. These "glitches" are your clues that what you are seeing might not be real.')
  }
];

// Helper for ticker symbols/logos -> Now "Topics"
export const getPublisherInfo = (publisher: string) => {
    // Map publishers (Topics) to colors/styles
    const map: Record<string, { logo: string, desc: string, color: string }> = {
       "Logic": { logo: "🧠", desc: "Critical Thinking", color: "#F7931A" },
       "Safety": { logo: "🛡️", desc: "Online Safety", color: "#627EEA" },
       "Data": { logo: "📊", desc: "Data Literacy", color: "#14F195" },
       "Ethics": { logo: "⚖️", desc: "AI Ethics", color: "#0033AD" },
       "Create": { logo: "🎨", desc: "Creative AI", color: "#E6007A" },
       "Social": { logo: "💬", desc: "Social Media", color: "#23292F" },
       "Future": { logo: "🚀", desc: "Future Skills", color: "#C2A633" },
       "Code": { logo: "💻", desc: "Coding Basics", color: "#2775CA" },
       "Bot": { logo: "🤖", desc: "Robotics", color: "#2A5ADA" },
       "Check": { logo: "✅", desc: "Fact Checking", color: "#8247E5" }
    };

    return map[publisher] || { 
        logo: publisher.substring(0, 1).toUpperCase(), 
        desc: "General Knowledge",
        color: "#6A4FBF"
    };
};

const MODULE_DATA = [
  {
    id: "ai-001",
    title: "The Algorithm Adventure",
    publisher: "Logic",
    year: "Ages 7-9",
    field: "Basics",
    link: "#",
    description: "Join AL-G, the friendly robot, as he sorts his room. Learn how algorithms are just step-by-step instructions for solving problems.",
    insights: ["Pattern Recognition", "Step-by-step logic", "Sequencing"],
    whyMatters: "Understanding algorithms is the first step to understanding how computers think.",
    authors: ["ClayMind Core"],
    readTime: "Beginner", // Difficulty
    image: "https://images.unsplash.com/photo-1518546305927-5a440dd2be94?auto=format&fit=crop&q=80&w=1200"
  },
  {
    id: "safe-001",
    title: "Digital Footprint Detective",
    publisher: "Safety",
    year: "Ages 10-12",
    field: "Privacy",
    link: "#",
    description: "Every click leaves a mark. In this game, you play a detective tracing where data goes when you sign up for a new app.",
    insights: ["Data Privacy", "Online Safety", "Permission settings"],
    whyMatters: "Protecting your personal information is crucial in a connected world.",
    authors: ["Safety First"],
    readTime: "Intermediate",
    image: "https://images.unsplash.com/photo-1622630998477-20aa696fa405?auto=format&fit=crop&q=80&w=1200"
  },
  {
    id: "fake-001",
    title: "Spot the Bot",
    publisher: "Check",
    year: "Ages 12-14",
    field: "Misinformation",
    link: "#",
    description: "Can you tell if a comment was written by a human or a bot? Analyze language patterns and profile pictures to uncover the truth.",
    insights: ["Critical Thinking", "Media Literacy", "Bot detection"],
    whyMatters: "Helps students navigate social media without being misled by automated accounts.",
    authors: ["Fact Squad"],
    readTime: "Advanced",
    image: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&q=80&w=1200"
  },
  {
    id: "eth-001",
    title: "The Bias Balloon",
    publisher: "Ethics",
    year: "Ages 10-14",
    field: "Fairness",
    link: "#",
    description: "Pop the balloons that contain biased statements. Learn how AI can accidentally learn unfair stereotypes from bad data.",
    insights: ["Fairness", "Data Quality", "Stereotype Awareness"],
    whyMatters: "Ensures the next generation builds inclusive technology.",
    authors: ["Ethics Lab"],
    readTime: "Intermediate",
    image: "https://images.unsplash.com/photo-1622630998477-20aa696fa405?auto=format&fit=crop&q=80&w=1200"
  },
  {
    id: "cre-001",
    title: "Prompt Painter",
    publisher: "Create",
    year: "Ages 7-14",
    field: "Generative AI",
    link: "#",
    description: "Learn how to talk to AI. Experiment with different words to see how they change the picture the AI draws.",
    insights: ["Prompt Engineering", "Creativity", "Vocabulary"],
    whyMatters: "Teaches that AI is a tool that requires clear human instruction.",
    authors: ["Art AI"],
    readTime: "Fun",
    image: "https://images.unsplash.com/photo-1622630998477-20aa696fa405?auto=format&fit=crop&q=80&w=1200"
  },
  {
    id: "dat-001",
    title: "Data Defender",
    publisher: "Data",
    year: "Ages 8-12",
    field: "Security",
    link: "#",
    description: "Build a fortress to protect your secrets. Learn about strong passwords and two-factor authentication in this tower defense game.",
    insights: ["Cybersecurity", "Passwords", "Encryption basics"],
    whyMatters: "Gamifies the boring but essential task of account security.",
    authors: ["ClayMind Core"],
    readTime: "Intermediate",
    image: "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?auto=format&fit=crop&q=80&w=1200"
  }
];

export const PAPERS: Paper[] = MODULE_DATA.map(item => ({
    id: item.id,
    title: item.title,
    publisher: item.publisher,
    authors: item.authors,
    abstractPreview: item.description,
    abstract: item.description,
    publicationDate: String(item.year),
    category: item.field, 
    doi: item.link,
    whyMatters: item.whyMatters,
    upvotes: Math.floor(Math.random() * 500) + 100, // XP Points
    timestamp: Date.now(), 
    aiInsights: item.insights,
    industry: [item.field],
    readTime: item.readTime, // Difficulty Level
    publisherLogo: getPublisherInfo(item.publisher).logo,
    fileUrl: item.image
}));